name: "Immich public proxy"
description: "Homeassistant addon containing an Immich public proxy"
version: "1.0.0"
slug: "imich_public_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
