name: "Immich public proxy"
description: "Homeassistant addon that wraps an Immich public proxy"
version: "1.0.0"
slug: "immich_public_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8443/tcp: 443